---
- name: Provision image
  hosts: default
  tasks:
    - name: Upgrade packages # noqa package-latest
      ansible.builtin.package:
        name: '*'
        state: latest

    - name: Install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - cloud-init
        - cloud-utils-growpart
        - dracut-config-generic
        - dnf-utils
        - gdisk
        - nfs-utils
        - qemu-guest-agent
        - rsync
        - tar
        - tuned
        - tcpdump
        - vim
        - jq
        - sudo
        - podman

    - name: Enable cloud-init services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
      loop:
        - cloud-config
        - cloud-init
        - cloud-init-local
        - cloud-final

    - name: Disable firstboot
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/firstboot
        regexp: '^RUN_FIRSTBOOT='
        line: 'RUN_FIRSTBOOT=NO'
        create: true
        owner: root
        group: root
        mode: '0644'
...
