---
- name: Provision image
  hosts: default
  tasks:
    - name: Upgrade packages
      ansible.builtin.package:
        name: '*'
        state: latest

    - name: Install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - cloud-init
        - gdisk
        - qemu-guest-agent
        - rsync
        - tar
        - tuned
        - tcpdump
        - vim
        - jq
        - sudo

    - name: Enable cloud-init services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
      with_items:
        - cloud-config
        - cloud-init
        - cloud-init-local
        - cloud-final

    - name: Disable firstboot
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/firstboot
        regexp: '^RUN_FIRSTBOOT='
        line: 'RUN_FIRSTBOOT=NO'
        create: true
        owner: root
        group: root
        mode: '0644'

    - name: Force classic ethX network interface naming
      block:
        - name: Disable predictable network interface names
          ansible.builtin.lineinfile:
            path: /etc/default/grub
            regexp: '^(GRUB_CMDLINE_LINUX=.*)'
            line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
            backrefs: yes

        - name: Update GRUB configuration
          ansible.builtin.command: >
            {{ 'grub2-mkconfig -o /boot/grub2/grub.cfg'
               if ansible_facts['os_family'] == 'RedHat'
               else 'update-grub' }}
          changed_when: true

        - name: Create udev rule to rename interfaces (fallback)
          ansible.builtin.copy:
            dest: /etc/udev/rules.d/80-net-setup-link.rules
            content: |
              # Disable predictable interface names
              SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", NAME="eth%n"
...
