name: Test Packer Builds

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check Packer format
        run: packer fmt -check -recursive .

  test-packer-install:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            test_build: ubuntu24
          - os: ubuntu-latest
            test_build: almalinux9
          - os: ubuntu-latest
            test_build: debian12
    name: Test Packer Installation for ${{ matrix.test_build }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup script
        run: |
          chmod +x ./scripts/setup
          ./scripts/setup

      - name: Check Packer version
        run: packer --version

      - name: Check Ansible version
        run: ansible --version

      - name: Check qemu-system version
        run:  qemu-system-x86_64 --version

      - name: Initialize Packer plugins
        run: packer init .

      - name: Validate Packer
        run: packer validate .
